config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  put 'tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :mark_as_done
  root to: 'tasks#index'
  # # read all tasks
  # get 'tasks', to: 'tasks#index'
  # # read one task / add a task / create it
  # get 'tasks/new', to: 'tasks#new'
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # post 'tasks', to: 'tasks#create'
  # # update one task
  # get 'tasks/:id/edit', to: 'tasks#edit'
  # patch 'tasks/:id', to: 'tasks#update'
  # # delete one task
  # delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_as_done]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  def mark_as_done
    if @task.completed == false
      @task.completed = true
    else
      @task.completed = false
    end
  @task.save
  redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="app/assets/stylesheets/application.scss">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <class class="app"></class>
    <%= yield %>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/create.hmtl.erb
<h1>What Task would you like to Create!</h1>

app/views/tasks/destroy.html.erb
<h1>Which Task do you want to Delete?</h1>

app/views/tasks/edit.html.erb
<h2>Lets Update your Task!</h2>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<body>
  <div class="big-container">
    <h2> My Task List</h2>
    <% @tasks.each do |task| %>
    <h4>
      <%= link_to mark_as_done_path(task), method: :put do %>
      <% if task.completed == true %>
      <i class="far fa-check-square"></i>
      <% else %>
      <i class="far fa-square"></i>
      <% end%>
      <% end %>
      <%= link_to "#{task.title.capitalize}", task_path(task.id) %>
    </h4>
    <% end %>
    <div class="button-comp">
      <button type="button" class="btn btn-primary"> <%= link_to "Add Task", new_task_path(@task) %>  </button>
    </div>
  </div>
</body>

app/views/tasks/new.html.erb
<h2>Add New Task</h2>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<body>

  <div class="header">
    <h4 class="show-header"><%= @task.title.capitalize %></h4>
  </div>

  <div class='small-container'>
    <p> <%=  @task.details.capitalize %> </p>
    <p> Task: <%= "#{@task.completed? ? 'Completed 😇' : 'Incomplete 😈'}" %> </p>
  </div>
  <div class="button-components">
    <button type="button" class="btn btn-success"> <%= link_to "Edit Task", edit_task_path(@task.id) %> </button>
    <button type="button" class="btn btn-primary"> <%= link_to "Back to Tasks list", tasks_path(@tasks) %> </button>
    <button type="button" class="btn btn-danger"> <%= link_to "Delete Task", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %> </button>
  </div>
</body>

app/views/tasks/update.html.erb
update.html.erb